# Generated by Django 3.0.3 on 2020-04-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200324_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='CPF',
            field=models.BigIntegerField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
