# Generated by Django 3.0.3 on 2020-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_auto_20200413_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='sus',
            field=models.BigIntegerField(default=701200076607217),
            preserve_default=False,
        ),
    ]
