# Generated by Django 3.0.3 on 2020-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.TextField()),
                ('possivel_depressao', models.BooleanField(default=False)),
                ('porcentagem_emocao1', models.CharField(max_length=4)),
                ('porcentagem_emocao2', models.CharField(max_length=3)),
                ('porcentagem_emocao3', models.CharField(max_length=3)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
