# Generated by Django 3.0.3 on 2020-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisevideo',
            name='porcentagem_emocao1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='porcentagem_emocao2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='porcentagem_emocao3',
            field=models.CharField(max_length=50),
        ),
    ]
