# Generated by Django 3.0.3 on 2020-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise_video', '0002_auto_20200324_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisevideo',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='porcentagem_emocao1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='porcentagem_emocao2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='porcentagem_emocao3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='possivel_depressao',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='analisevideo',
            name='relatorio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
