# Generated by Django 3.0.3 on 2020-04-04 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialista', '0013_auto_20200404_1953'),
        ('paciente', '0003_auto_20200324_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistaPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialista.Especialista')),
            ],
        ),
    ]
