# Generated by Django 3.0.3 on 2020-05-01 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista_paciente', '0002_auto_20200407_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistapaciente',
            old_name='specialist',
            new_name='especialista',
        ),
    ]
