# Generated by Django 3.0.3 on 2020-03-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('video', models.CharField(max_length=250)),
                ('sono_alterado', models.BooleanField(default=False)),
                ('peso_alterado', models.BooleanField(default=False)),
                ('apetite_alterado', models.BooleanField(default=False)),
            ],
        ),
    ]
