# Generated by Django 3.0.3 on 2020-03-26 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200324_1516'),
        ('analise_video', '0002_auto_20200324_1601'),
        ('especialista', '0006_auto_20200324_1959'),
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='analise_video',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='analise_video.AnaliseVideo'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='especialista',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='especialista.Especialista'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente'),
        ),
    ]
