# Generated by Django 3.0.3 on 2020-06-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_auto_20200501_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='relatorio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
