# Generated by Django 3.0.3 on 2020-06-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_auto_20200603_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
