# Generated by Django 3.0.3 on 2020-06-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_auto_20200603_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='video_teste',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
