# Generated by Django 3.0.3 on 2020-06-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_consulta_video_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='video',
        ),
    ]
