# Generated by Django 3.0.3 on 2020-06-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0012_remove_consulta_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='video_teste',
            new_name='video',
        ),
    ]
