# Generated by Django 3.0.3 on 2020-03-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0005_auto_20200324_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='telefone',
            field=models.BigIntegerField(),
        ),
    ]
