# Generated by Django 3.0.3 on 2020-03-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200324_1516'),
        ('especialista', '0006_auto_20200324_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialistaPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(auto_now_add=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialista.Especialista')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='especialista',
            name='pacientes',
            field=models.ManyToManyField(through='especialista.EspecialistaPaciente', to='paciente.Paciente'),
        ),
    ]
