# Generated by Django 3.0.3 on 2020-04-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0007_auto_20200326_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistapaciente',
            old_name='paciente',
            new_name='pacienteId',
        ),
    ]
