# Generated by Django 3.0.3 on 2020-04-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0008_auto_20200401_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialistapaciente',
            old_name='pacienteId',
            new_name='pac',
        ),
        migrations.RenameField(
            model_name='especialistapaciente',
            old_name='especialista',
            new_name='specialist',
        ),
    ]
