# Generated by Django 3.0.3 on 2020-04-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0009_auto_20200401_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialista',
            old_name='pacientes',
            new_name='pacS',
        ),
    ]
