# Generated by Django 3.0.3 on 2020-04-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200324_1516'),
        ('especialista', '0011_auto_20200401_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialistapaciente',
            name='pac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pac', to='paciente.Paciente'),
        ),
    ]
