# Generated by Django 3.0.3 on 2020-04-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_auto_20200324_1516'),
        ('especialista', '0013_auto_20200404_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='paci',
            field=models.ManyToManyField(to='paciente.Paciente'),
        ),
    ]
