# Generated by Django 3.0.3 on 2020-06-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0016_especialista_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='teste',
            field=models.FileField(blank=True, null=True, upload_to='teste'),
        ),
    ]
