# Generated by Django 3.0.3 on 2020-06-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0017_especialista_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='imagem_perfil',
        ),
    ]
